export { analyze, analyzeFederation } from "./engine.js";
export {
  resolveOptions,
  resolveQuiet,
  resolvePrintLog,
  isCiEnvironment,
  DEFAULT_EXCLUDE,
  DEFAULT_INCLUDE,
} from "./config.js";
export {
  applyBaseline,
  entryMatchesFinding,
  generateBaseline,
  loadBaseline,
  parseBaseline,
  policyFails,
  policyRelevantFindings,
  pruneBaseline,
  resolveBaselineOptions,
  summarizeFindings,
  updateBaseline,
  writeBaselineFile,
} from "./baseline.js";
export {
  DEFAULT_WORKSPACE_PROJECT_GLOBS,
  WORKSPACE_IGNORE,
  discoverWorkspaceProjects,
} from "./workspace.js";
export type { DiscoverWorkspaceProjectsOptions } from "./workspace.js";
export {
  DOCTOR_PRESET_NAMES,
  definePolicyPack,
  isDoctorPresetName,
  presets,
  recommendedPreset,
  resolvePolicy,
  strictPreset,
} from "./policy.js";
export { defineRule, builtInRules } from "./rules.js";
export { ProbeError, probeManifest } from "./probe.js";
export {
  RuntimeTraceError,
  analyzeRuntime,
  correlateRuntime,
  loadRuntimeTraceFile,
  parseRuntimeTraces,
} from "./runtime-trace.js";
export { buildUiPayload } from "./ui-graph.js";
export {
  EVIDENCE_LEGACY_ENV,
  RELEASE_GATES,
  ROLLOUT_SCOPES,
  RolloutGateError,
  createEvidenceRolloutController,
} from "./evidence-rollout.js";
export type {
  EvidenceRolloutController,
  EvidenceRolloutOptions,
  ReleaseGate,
  ReleaseGateStatus,
  RolloutMode,
  RolloutScope,
  ScopedRolloutModes,
} from "./evidence-rollout.js";
export type { ManifestProbeResult, ProbeOptions } from "./probe.js";
export type { ApplyBaselineResult, ResolvedBaselineOptions } from "./baseline.js";
export {
  DEFAULT_ALWAYS_SHARED,
  DEFAULT_DEEP_IMPORT_ALLOWLIST,
  DEFAULT_IMPORT_DEPTH,
  DEFAULT_SHARE_CANDIDATE_PACKAGES,
  DEFAULT_SINGLETON_RISK_PACKAGES,
  mergeSharedPolicy,
} from "./shared-policy.js";
export type {
  AnalysisCapabilities,
  AnalysisResult,
  ArtifactFacts,
  BaselineEntry,
  BaselineFile,
  BaselineOptions,
  BundlerFacts,
  BundlerName,
  ViteLifecycleEngine,
  ViteLifecycleFacts,
  ViteLifecycleFlavor,
  DependencyFacts,
  DoctorExtendEntry,
  DoctorFinding,
  DoctorOptions,
  DoctorPolicyPack,
  DoctorPresetName,
  DoctorPrintLog,
  DoctorReport,
  DoctorRule,
  DoctorSharedPolicy,
  DoctorUiPayload,
  FederationAnalysisResult,
  ImportDepth,
  ImportEvidenceSource,
  ImportFacts,
  ModuleFederationConfigLike,
  UnresolvedDynamicApi,
  UnresolvedDynamicImport,
  NormalizedMFConfig,
  OutputFormat,
  OutputPublicPathKind,
  ProjectFacts,
  ProjectIdentity,
  ResolvedDoctorOptions,
  RuleContext,
  RuleMeta,
  RuleSetting,
  RuntimeAnalysisResult,
  RuntimeTraceReport,
  Severity,
  SourceLocation,
  UiGraph,
  UiGraphEdge,
  UiGraphNode,
  UiGraphNodeKind,
} from "./types.js";
export {
  canonicalIdentityKey,
  createAdapterTargetIdentity,
  createApplicationIdentity,
  createArtifactIdentity,
  createBuildIdentity,
  createBuildLineageIdentity,
  createContainerIdentity,
  createDeploymentIdentity,
  createEnvironmentIdentity,
  createIdentity,
  createOrganizationIdentity,
  createRuntimeInstanceIdentity,
  createRuntimeRealmIdentity,
  IDENTITY_SCHEMA_VERSION,
  unknownIdentity,
} from "./identity.js";
export type {
  AdapterTargetIdentity,
  AdapterTargetDimensions,
  AnySemanticIdentity,
  ApplicationDimensions,
  ApplicationIdentity,
  ArtifactDimensions,
  ArtifactIdentity,
  BuildDimensions,
  BuildIdentity,
  BuildLineageDimensions,
  BuildLineageIdentity,
  ContainerDimensions,
  ContainerIdentity,
  CreateIdentityOptions,
  DeploymentIdentity,
  DeploymentDimensions,
  EnvironmentDimensions,
  EnvironmentIdentity,
  IdentityCompleteness,
  IdentityConfidence,
  IdentityChildOptions,
  IdentityDimensions,
  IdentityKind,
  IdentityDimensionsByKind,
  IdentityOptions,
  IdentityRealm,
  IdentityTarget,
  OrganizationDimensions,
  IdentityProvenance,
  IdentitySchemaVersion,
  OrganizationIdentity,
  RuntimeInstanceIdentity,
  RuntimeRealmIdentity,
  RuntimeRealmDimensions,
  RuntimeInstanceDimensions,
  SemanticIdentity,
} from "./identity.js";
export {
  assertEvidenceGraphIntegrity,
  assertEvidenceValue,
  canonicalizeEvidenceValue,
  normalizeEvidenceGraph,
  redactEvidenceValue,
  stableEvidenceId,
} from "./evidence.js";
export { EvidenceIntegrityError, EvidenceResourceError } from "./evidence.js";
export type {
  EvidenceAssertion,
  EvidenceCompleteness,
  EvidenceCompletenessInfo,
  EvidenceConfidence,
  EvidenceConfidenceInfo,
  EvidenceEdge,
  EvidenceEdgeKind,
  EvidenceGraphV2,
  EvidenceIdentity,
  EvidenceLayer,
  EvidenceLimits,
  EvidenceProtocolIdentity,
  EvidenceProtocolVersion,
  EvidenceProvenance,
  EvidenceRuleEvaluation,
  EvidenceScope,
  EvidenceSubject,
  EvidenceSubjectKind,
  EvidenceValue,
  RuleOutcome,
} from "./evidence.js";
