import type {
  EvidenceAwareRuleMeta,
  EvidenceRequirement,
  RuleApplicability,
} from "./rule-contract.js";
import { ruleGuidance } from "./rule-guidance.js";

export type RuleMigrationGroup = 0 | 1 | 2 | 3 | 4 | 5 | 6;
export type RuleMigrationStatus = "legacy" | "migrated";

/** Documented compatibility-only built-ins that intentionally stay off the evidence bridge. */
export interface RuleCompatibilityException {
  id: string;
  owner: { name: string; contact?: string };
  reason: string;
  scope: string;
  deprecationPlan: string;
}

/** Empty by design for V1 closeout — every current built-in is migrated. */
export const RULE_COMPATIBILITY_EXCEPTIONS: readonly RuleCompatibilityException[] = Object.freeze(
  [],
);

export interface RuleInventoryEntry extends EvidenceAwareRuleMeta {
  group: RuleMigrationGroup;
  status: RuleMigrationStatus;
  migrationNote: string;
  /** Fact paths read by the legacy implementation; prerequisites must cover every path. */
  evidenceReads: readonly string[];
}

const ids = [
  "artifact/dts-disabled",
  "artifact/expose-missing",
  "artifact/manifest-assets-disabled",
  "artifact/manifest-disabled",
  "artifact/manifest-expose-assets-empty",
  "artifact/manifest-invalid",
  "artifact/manifest-name-mismatch",
  "artifact/manifest-remote-entry-missing",
  "artifact/manifest-shared-version-mismatch",
  "artifact/public-path-non-string-manifest",
  "artifact/public-path-suspicious",
  "artifact/react-dom-server-in-web",
  "artifact/remote-entry-missing",
  "artifact/types-metadata-missing",
  "artifact/types-missing",
  "bridge/consumer-api-manual",
  "bridge/disable-alias-deprecated",
  "bridge/export-app-missing",
  "bridge/lazy-plugin-unregistered",
  "bridge/missing-fallback-loading",
  "bridge/provider-shape-invalid",
  "bridge/react-dom-prefix-missing",
  "bridge/react-version-entry-mismatch",
  "bridge/react-version-entry-prefer",
  "bridge/router-implicit-enable",
  "bridge/router-shared-conflict",
  "bridge/ssr-instanceid-hydration",
  "bridge/ssr-server-entry-leak",
  "bridge/tanstack-router-conflict",
  "bridge/vue-consumer-manual",
  "bridge/vue-server-entry",
  "bridge/vue-share-missing",
  "bridge/vue-ssr-fresh-context",
  "config/copied-webpack-options-on-vite",
  "config/dts-output-dir-mismatch",
  "config/duplicate-plugin-registration",
  "config/async-boundary-missing",
  "config/eager-tree-shaking-conflict",
  "config/expose-key-invalid",
  "config/expose-path-missing",
  "config/external-runtime-conflict",
  "config/external-runtime-with-exposes",
  "config/filename-invalid",
  "config/get-public-path-invalid",
  "config/get-public-path-unused",
  "config/implementation-suspicious",
  "config/library-remote-type-mismatch",
  "config/name-required",
  "config/plugin-package-mismatch",
  "config/remote-alias-prefix-collision",
  "config/remote-capability-disabled",
  "config/remote-entry-invalid",
  "config/remote-http-insecure",
  "config/remote-localhost-in-production",
  "config/remote-manifest-recommended",
  "config/observability-plugin-recommended",
  "config/rsbuild-mf-api-generation",
  "config/runtime-plugin-missing",
  "config/share-scope-undeclared",
  "config/shared-capability-disabled",
  "config/tree-shaking-server-calc-injection",
  "doctor/partial-analysis",
  "federation/circular-remote-graph",
  "federation/external-runtime-provider-missing",
  "federation/ghost-shares",
  "federation/host-gaps",
  "federation/missing-provider",
  "federation/name-conflict",
  "federation/share-scope-mismatch",
  "federation/share-strategy-mismatch",
  "federation/version-conflict",
  "performance/asset-budget",
  "performance/version-first-startup",
  "performance/vite-bundle-all-css",
  "reliability/async-startup-library-promise",
  "reliability/external-runtime-provider-unverified",
  "reliability/shared-import-false",
  "reliability/snapshot-capability-disabled",
  "reliability/tree-shaking-server-calc-contract",
  "reliability/version-first-offline-remotes",
  "reliability/vite-fixed-parse-timeout",
  "vite/remotes-prefer-module",
  "vite/var-filename-interop",
  "vite/host-init-inject-ssr",
  "vite/ssr-nitro-externals",
  "vite/manual-chunks-conflict",
  "vite/hashed-remote-filename",
  "vite/remote-hmr-dev",
  "vite/alias-share-bypass",
  "vite/server-origin",
  "config/transform-import-share-conflict",
  "runtime/error-correlated",
  "runtime/init-failed",
  "runtime/remote-load-failed",
  "runtime/remote-unknown",
  "runtime/shared-mismatch",
  "runtime-plugins/create-script-cors-parity",
  "runtime-plugins/create-script-without-link",
  "runtime-plugins/invalid-factory",
  "security/get-public-path-dynamic-code",
  "shared/candidate",
  "shared/react-host-missing",
  "shared/deep-import-bypass",
  "shared/prefix-share-recommended",
  "shared/subpath-version-unresolved",
  "shared/eager-without-singleton",
  "shared/singleton-mismatch",
  "shared/singleton-risk",
  "shared/unused",
  "shared/version-unsatisfied",
  "ssr/node-library-dts",
  "ssr/node-remote-manifest",
  "ssr/node-runtime-plugin-missing",
] as const;

/** Group 1 core-configuration rules promoted by the staged V1 rollout. */
export const MIGRATED_GROUP1_CONFIG_RULE_IDS = [
  "config/name-required",
  "config/expose-key-invalid",
  "config/expose-path-missing",
  "config/remote-entry-invalid",
  "config/filename-invalid",
  "config/remote-http-insecure",
  "config/remote-localhost-in-production",
  "config/remote-alias-prefix-collision",
  "config/dts-output-dir-mismatch",
  "config/remote-manifest-recommended",
  "config/observability-plugin-recommended",
  "config/library-remote-type-mismatch",
  "config/share-scope-undeclared",
  "config/runtime-plugin-missing",
  "config/get-public-path-invalid",
  "config/get-public-path-unused",
  "config/implementation-suspicious",
  "config/external-runtime-with-exposes",
  "config/remote-capability-disabled",
  "config/shared-capability-disabled",
  "config/eager-tree-shaking-conflict",
  "config/async-boundary-missing",
  "config/tree-shaking-server-calc-injection",
  "config/rsbuild-mf-api-generation",
] as const;

/** Group 1 Bridge, SSR, and runtime-plugin rules promoted by the staged V1 rollout. */
export const MIGRATED_GROUP1_BRIDGE_SSR_RUNTIME_PLUGIN_RULE_IDS = [
  "bridge/react-version-entry-prefer",
  "bridge/react-dom-prefix-missing",
  "bridge/lazy-plugin-unregistered",
  "bridge/router-implicit-enable",
  "bridge/router-shared-conflict",
  "bridge/react-version-entry-mismatch",
  "bridge/provider-shape-invalid",
  "bridge/ssr-server-entry-leak",
  "bridge/missing-fallback-loading",
  "bridge/consumer-api-manual",
  "bridge/export-app-missing",
  "bridge/ssr-instanceid-hydration",
  "bridge/tanstack-router-conflict",
  "bridge/disable-alias-deprecated",
  "bridge/vue-share-missing",
  "bridge/vue-ssr-fresh-context",
  "bridge/vue-server-entry",
  "bridge/vue-consumer-manual",
  "ssr/node-remote-manifest",
  "ssr/node-runtime-plugin-missing",
  "ssr/node-library-dts",
  "runtime-plugins/invalid-factory",
  "runtime-plugins/create-script-cors-parity",
  "runtime-plugins/create-script-without-link",
] as const;

export const MIGRATED_GROUP2_RULE_IDS = [
  "config/duplicate-plugin-registration",
  "artifact/public-path-non-string-manifest",
  "config/external-runtime-conflict",
  "performance/asset-budget",
  "artifact/manifest-assets-disabled",
  "artifact/manifest-disabled",
  "artifact/dts-disabled",
  "artifact/manifest-invalid",
  "artifact/manifest-name-mismatch",
  "artifact/manifest-remote-entry-missing",
  "artifact/manifest-expose-assets-empty",
  "artifact/manifest-shared-version-mismatch",
  "artifact/types-metadata-missing",
  "artifact/remote-entry-missing",
  "artifact/expose-missing",
  "artifact/public-path-suspicious",
  "artifact/react-dom-server-in-web",
  "artifact/types-missing",
] as const;

/** Group 3 source and package heuristic rules promoted by the staged V1 rollout. */
export const MIGRATED_GROUP3_RULE_IDS = [
  "security/get-public-path-dynamic-code",
  "shared/version-unsatisfied",
  "config/plugin-package-mismatch",
  "shared/singleton-risk",
  "shared/eager-without-singleton",
  "shared/unused",
  "shared/candidate",
  "shared/react-host-missing",
  "shared/deep-import-bypass",
  "shared/prefix-share-recommended",
  "shared/subpath-version-unresolved",
] as const;

/** Group 4 federation workspace topology rules promoted by the staged V1 rollout. */
export const MIGRATED_GROUP4_RULE_IDS = [
  "federation/name-conflict",
  "federation/version-conflict",
  "federation/share-scope-mismatch",
  "federation/share-strategy-mismatch",
  "federation/circular-remote-graph",
  "federation/missing-provider",
  "federation/host-gaps",
  "federation/ghost-shares",
  "shared/singleton-mismatch",
  "federation/external-runtime-provider-missing",
] as const;

/** Group 5 imported runtime-correlated rules promoted by the staged V1 rollout. */
export const MIGRATED_GROUP5_RULE_IDS = [
  "runtime/remote-load-failed",
  "runtime/init-failed",
  "runtime/shared-mismatch",
  "runtime/remote-unknown",
  "runtime/error-correlated",
] as const;

/** Group 6 reliability, performance, and Vite dialect rules promoted by the staged V1 rollout. */
export const MIGRATED_GROUP6_RULE_IDS = [
  "reliability/snapshot-capability-disabled",
  "reliability/external-runtime-provider-unverified",
  "reliability/async-startup-library-promise",
  "performance/version-first-startup",
  "reliability/version-first-offline-remotes",
  "reliability/shared-import-false",
  "reliability/tree-shaking-server-calc-contract",
  "performance/vite-bundle-all-css",
  "reliability/vite-fixed-parse-timeout",
  "vite/remotes-prefer-module",
  "vite/var-filename-interop",
  "vite/host-init-inject-ssr",
  "vite/ssr-nitro-externals",
  "vite/manual-chunks-conflict",
  "vite/hashed-remote-filename",
  "vite/remote-hmr-dev",
  "vite/alias-share-bypass",
  "vite/server-origin",
  "config/transform-import-share-conflict",
  "config/copied-webpack-options-on-vite",
  "doctor/partial-analysis",
] as const;

/** Every built-in promoted through the V1 evidence-aware migration groups 1–6. */
export const ALL_MIGRATED_RULE_IDS = Object.freeze([
  ...MIGRATED_GROUP1_CONFIG_RULE_IDS,
  ...MIGRATED_GROUP1_BRIDGE_SSR_RUNTIME_PLUGIN_RULE_IDS,
  ...MIGRATED_GROUP2_RULE_IDS,
  ...MIGRATED_GROUP3_RULE_IDS,
  ...MIGRATED_GROUP4_RULE_IDS,
  ...MIGRATED_GROUP5_RULE_IDS,
  ...MIGRATED_GROUP6_RULE_IDS,
] as const);

const MIGRATED_RULE_IDS: ReadonlySet<string> = new Set(ALL_MIGRATED_RULE_IDS);
const COMPATIBILITY_EXCEPTION_IDS = new Set(RULE_COMPATIBILITY_EXCEPTIONS.map((entry) => entry.id));

type RulePlan = {
  group: RuleMigrationGroup;
  severity: "error" | "warning" | "info";
  predicate: string;
  layer: "declared" | "artifact" | "runtime";
  subjectKind:
    | "project"
    | "dependency"
    | "remote"
    | "shared-package"
    | "build"
    | "artifact"
    | "runtime-instance";
  confidenceCeiling: "exact" | "high" | "medium" | "low" | "unknown";
  adapters: readonly string[];
  bundlers: readonly string[];
  confidenceReason: string;
};

const ALL = ["vite", "rspack", "rsbuild", "webpack", "modern"] as const;
const VITE = ["vite"] as const;
const RSBUILD = ["rsbuild"] as const;
const plan = (
  group: RuleMigrationGroup,
  severity: RulePlan["severity"],
  predicate: string,
  layer: RulePlan["layer"],
  subjectKind: RulePlan["subjectKind"],
  confidenceCeiling: RulePlan["confidenceCeiling"],
  confidenceReason: string,
  bundlers: readonly string[] = ALL,
): RulePlan => ({
  group,
  severity,
  predicate,
  layer,
  subjectKind,
  confidenceCeiling,
  adapters: bundlers,
  bundlers,
  confidenceReason,
});

/** Explicit plan for every current built-in. No plan may fall back to a group default. */
const plans: Record<string, RulePlan> = {
  "config/name-required": plan(
    1,
    "error",
    "project.moduleFederation",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/expose-key-invalid": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/expose-path-missing": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/remote-entry-invalid": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/filename-invalid": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/remote-http-insecure": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/remote-localhost-in-production": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/duplicate-plugin-registration": plan(
    2,
    "error",
    "compiler.plugin-registration",
    "artifact",
    "build",
    "exact",
    "Compiler registration evidence is exact when collected.",
  ),
  "config/remote-alias-prefix-collision": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/dts-output-dir-mismatch": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "artifact/public-path-non-string-manifest": plan(
    2,
    "warning",
    "artifact.manifest",
    "artifact",
    "artifact",
    "exact",
    "Parsed manifest evidence is exact when valid.",
  ),
  "config/remote-manifest-recommended": plan(
    1,
    "info",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/observability-plugin-recommended": plan(
    1,
    "info",
    "config.declared + source.scan",
    "declared",
    "project",
    "medium",
    "Declared package versions and static runtime registrations are exact when dependency and source facts are complete.",
  ),
  "config/library-remote-type-mismatch": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/share-scope-undeclared": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/runtime-plugin-missing": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "runtime-plugins/invalid-factory": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Local plugin source is readable; unreadable modules are skipped.",
  ),
  "runtime-plugins/create-script-cors-parity": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Clear CORS asymmetry from local plugin source text.",
  ),
  "runtime-plugins/create-script-without-link": plan(
    1,
    "info",
    "config.declared",
    "declared",
    "project",
    "medium",
    "Heuristic createScript-without-createLink when CORS attrs are not confirmed.",
  ),
  "config/get-public-path-invalid": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/get-public-path-unused": plan(
    1,
    "info",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "security/get-public-path-dynamic-code": plan(
    3,
    "warning",
    "source.scan",
    "declared",
    "project",
    "low",
    "Source scans are heuristic and cannot claim exact confidence.",
  ),
  "config/implementation-suspicious": plan(
    1,
    "info",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/external-runtime-with-exposes": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/external-runtime-conflict": plan(
    2,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/remote-capability-disabled": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/shared-capability-disabled": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "reliability/snapshot-capability-disabled": plan(
    6,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared snapshot/disable and manifest facts are exact for this shape check.",
  ),
  "config/eager-tree-shaking-conflict": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/async-boundary-missing": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Host remotes/shared config plus readable entry sources are exact when source scan is complete.",
  ),
  "reliability/external-runtime-provider-unverified": plan(
    6,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared externalRuntime experiments are exact for this verification advisory.",
  ),
  "reliability/async-startup-library-promise": plan(
    6,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared asyncStartup and library.type facts are exact for this contract advisory.",
  ),
  "performance/version-first-startup": plan(
    6,
    "info",
    "config.declared",
    "declared",
    "project",
    "medium",
    "Declared shareStrategy and remote count are exact for this startup advisory.",
  ),
  "performance/asset-budget": plan(
    2,
    "warning",
    "artifact.asset-size",
    "artifact",
    "artifact",
    "exact",
    "Collected asset sizes are exact when complete.",
  ),
  "reliability/version-first-offline-remotes": plan(
    6,
    "warning",
    "config.declared",
    "declared",
    "project",
    "medium",
    "Declared shareStrategy, remotes, and runtimePlugins are exact; demo soft-path uses MFDoctor analysis mode.",
  ),
  "reliability/shared-import-false": plan(
    6,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared shared.import facts are exact for this fallback advisory.",
  ),
  "config/tree-shaking-server-calc-injection": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "reliability/tree-shaking-server-calc-contract": plan(
    6,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared treeShaking directory and shared tree-shaking mode are exact for this contract check.",
  ),
  "performance/vite-bundle-all-css": plan(
    6,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared bundleAllCSS and expose count are exact for this Vite advisory.",
    VITE,
  ),
  "reliability/vite-fixed-parse-timeout": plan(
    6,
    "info",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared moduleParseTimeout facts are exact for this Vite advisory.",
    VITE,
  ),
  "vite/remotes-prefer-module": plan(
    6,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared remotes typing is exact; missing type is treated as Vite default var without inventing type on normalize.",
    VITE,
  ),
  "vite/var-filename-interop": plan(
    6,
    "info",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared varFilename plus remotes typing is exact for the intentional interop path.",
    VITE,
  ),
  "vite/host-init-inject-ssr": plan(
    6,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "SSR signals from vite.target, experiments.target, builds.targetKind=ssr, or framework deps gate this declared inject check. Bare builds.targetKind=node is ignored (Vite default ssr.target).",
    VITE,
  ),
  "vite/ssr-nitro-externals": plan(
    6,
    "warning",
    "config.declared",
    "declared",
    "project",
    "medium",
    "Requires SSR/Nitro signals plus shared React and ssrExternals or ssrEntryLoader facts; otherwise skips. Bare builds.targetKind=node is ignored.",
    VITE,
  ),
  "vite/manual-chunks-conflict": plan(
    6,
    "info",
    "config.declared",
    "declared",
    "project",
    "high",
    "Absent plugin viteConfig facts → unknown; observed empty manualChunks/codeSplittingGroups → pass.",
    VITE,
  ),
  "vite/hashed-remote-filename": plan(
    6,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared filename pattern check; skips when filename absent.",
    VITE,
  ),
  "vite/remote-hmr-dev": plan(
    6,
    "info",
    "config.declared",
    "declared",
    "project",
    "high",
    "Only fires when remoteHmr is explicitly false in MFDoctor development mode or a single unscoped project build effectiveMode; unknown skips.",
    VITE,
  ),
  "vite/alias-share-bypass": plan(
    6,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Absent plugin viteConfig facts → unknown; observed empty or no shared overlap → pass.",
    VITE,
  ),
  "vite/server-origin": plan(
    6,
    "info",
    "config.declared",
    "declared",
    "project",
    "high",
    "Absent plugin server.origin fact → unknown; observed matching origin → pass.",
    VITE,
  ),
  "config/transform-import-share-conflict": plan(
    6,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Requires transformImport library facts from options/adapters; skips when unknown.",
  ),
  "config/copied-webpack-options-on-vite": plan(
    6,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared webpack-only options on Vite federation config are exact; quiet when none are present.",
    VITE,
  ),
  "artifact/manifest-assets-disabled": plan(
    2,
    "warning",
    "artifact.manifest",
    "artifact",
    "artifact",
    "exact",
    "Parsed manifest evidence is exact when valid.",
  ),
  "artifact/manifest-disabled": plan(
    2,
    "warning",
    "artifact.manifest",
    "artifact",
    "artifact",
    "exact",
    "Parsed manifest evidence is exact when valid.",
  ),
  "artifact/dts-disabled": plan(
    2,
    "warning",
    "artifact.types",
    "artifact",
    "artifact",
    "exact",
    "Collected type artifact evidence is exact when complete.",
  ),
  "shared/version-unsatisfied": plan(
    3,
    "error",
    "dependency.package",
    "declared",
    "project",
    "medium",
    "Package metadata is exact only after provenance and version resolution are verified.",
  ),
  "artifact/manifest-invalid": plan(
    2,
    "error",
    "artifact.manifest.validity",
    "artifact",
    "artifact",
    "exact",
    "Parsed manifest evidence is exact when valid.",
  ),
  "artifact/manifest-name-mismatch": plan(
    2,
    "error",
    "artifact.manifest",
    "artifact",
    "artifact",
    "exact",
    "Parsed manifest evidence is exact when valid.",
  ),
  "artifact/manifest-remote-entry-missing": plan(
    2,
    "error",
    "artifact.manifest",
    "artifact",
    "artifact",
    "exact",
    "Parsed manifest evidence is exact when valid.",
  ),
  "artifact/manifest-expose-assets-empty": plan(
    2,
    "warning",
    "artifact.manifest",
    "artifact",
    "artifact",
    "exact",
    "Parsed manifest evidence is exact when valid.",
  ),
  "artifact/manifest-shared-version-mismatch": plan(
    2,
    "warning",
    "artifact.manifest",
    "artifact",
    "artifact",
    "exact",
    "Parsed manifest evidence is exact when valid.",
  ),
  "artifact/types-metadata-missing": plan(
    2,
    "warning",
    "artifact.types",
    "artifact",
    "artifact",
    "exact",
    "Collected type artifact evidence is exact when complete.",
  ),
  "artifact/remote-entry-missing": plan(
    2,
    "error",
    "artifact.remote-entry",
    "artifact",
    "artifact",
    "exact",
    "Collected remote entry evidence is exact when complete.",
  ),
  "artifact/expose-missing": plan(
    2,
    "error",
    "artifact.expose",
    "artifact",
    "artifact",
    "exact",
    "Collected expose artifact evidence is exact when complete.",
  ),
  "doctor/partial-analysis": plan(
    6,
    "warning",
    "analysis.capability",
    "declared",
    "project",
    "unknown",
    "Capability evidence is not yet normalized by the evidence protocol.",
  ),
  "config/plugin-package-mismatch": plan(
    3,
    "warning",
    "dependency.package",
    "declared",
    "project",
    "medium",
    "Package metadata is exact only after provenance and version resolution are verified.",
  ),
  "config/rsbuild-mf-api-generation": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared Rsbuild MF option keys are exact for the 1.5 vs plugin v2 surface check.",
    RSBUILD,
  ),
  "shared/singleton-risk": plan(
    3,
    "warning",
    "dependency.package",
    "declared",
    "project",
    "low",
    "Shared package scans are heuristic and cannot claim exact confidence.",
  ),
  "shared/eager-without-singleton": plan(
    3,
    "warning",
    "dependency.package",
    "declared",
    "project",
    "low",
    "Shared package scans are heuristic and cannot claim exact confidence.",
  ),
  "shared/unused": plan(
    3,
    "warning",
    "source.scan",
    "declared",
    "project",
    "low",
    "Absence from a source scan is heuristic and needs complete scan evidence.",
  ),
  "shared/candidate": plan(
    3,
    "info",
    "source.scan",
    "declared",
    "project",
    "low",
    "Shared package scans are heuristic and cannot claim exact confidence.",
  ),
  "shared/react-host-missing": plan(
    3,
    "warning",
    "config.declared + source.scan",
    "declared",
    "project",
    "medium",
    "Configured remotes and static React imports are exact for the host shape; package sharing remains a declared configuration recommendation.",
  ),
  "shared/deep-import-bypass": plan(
    3,
    "warning",
    "source.scan",
    "declared",
    "project",
    "low",
    "Shared package scans are heuristic and cannot claim exact confidence.",
  ),
  "shared/prefix-share-recommended": plan(
    3,
    "error",
    "config.declared + source.scan",
    "declared",
    "project",
    "high",
    "Observed deep-import and declared shared-key facts are exact when source collection is complete.",
  ),
  "shared/subpath-version-unresolved": plan(
    3,
    "error",
    "config.declared + dependency.package",
    "declared",
    "project",
    "high",
    "Vite prefix/subpath share keys plus installed parent-package versions are exact when installedVersions collection completed.",
    VITE,
  ),
  "artifact/public-path-suspicious": plan(
    2,
    "warning",
    "artifact.public-path",
    "artifact",
    "artifact",
    "high",
    "Artifact public-path evidence is exact when the artifact is complete.",
  ),
  "artifact/react-dom-server-in-web": plan(
    2,
    "error",
    "artifact.web + source.scan",
    "artifact",
    "artifact",
    "high",
    "Web-target and react-dom/server import/shared/artifact signals are exact when source and artifact facts are complete.",
  ),
  "artifact/types-missing": plan(
    2,
    "warning",
    "artifact.types",
    "artifact",
    "artifact",
    "exact",
    "Collected type artifact evidence is exact when complete.",
  ),
  "federation/name-conflict": plan(
    4,
    "error",
    "federation.graph",
    "declared",
    "project",
    "high",
    "Federation graph evidence is high confidence when all projects are present.",
  ),
  "federation/version-conflict": plan(
    4,
    "error",
    "federation.graph",
    "declared",
    "shared-package",
    "high",
    "Federation graph evidence is high confidence when all projects are present.",
  ),
  "federation/share-scope-mismatch": plan(
    4,
    "error",
    "federation.graph",
    "declared",
    "shared-package",
    "high",
    "Federation graph evidence is high confidence when all projects are present.",
  ),
  "federation/share-strategy-mismatch": plan(
    4,
    "warning",
    "federation.graph",
    "declared",
    "project",
    "high",
    "Federation graph evidence is high confidence when all projects are present.",
  ),
  "federation/circular-remote-graph": plan(
    4,
    "warning",
    "federation.graph",
    "declared",
    "remote",
    "high",
    "Federation graph evidence is high confidence when all projects are present.",
  ),
  "federation/missing-provider": plan(
    4,
    "error",
    "federation.graph",
    "declared",
    "shared-package",
    "high",
    "Federation graph evidence is high confidence when all projects are present.",
  ),
  "federation/host-gaps": plan(
    4,
    "warning",
    "federation.graph",
    "declared",
    "project",
    "high",
    "Federation graph evidence is high confidence when all projects are present.",
  ),
  "federation/ghost-shares": plan(
    4,
    "info",
    "federation.graph",
    "declared",
    "shared-package",
    "high",
    "Federation graph evidence is high confidence when all projects are present.",
  ),
  "shared/singleton-mismatch": plan(
    4,
    "warning",
    "federation.graph",
    "declared",
    "shared-package",
    "high",
    "Federation graph evidence is high confidence when all projects are present.",
  ),
  "federation/external-runtime-provider-missing": plan(
    4,
    "error",
    "federation.graph",
    "declared",
    "project",
    "high",
    "Federation graph evidence is high confidence when all projects are present.",
  ),
  "runtime/remote-load-failed": plan(
    5,
    "error",
    "runtime.trace",
    "runtime",
    "runtime-instance",
    "high",
    "Imported runtime trace evidence is high confidence when attributed.",
  ),
  "runtime/init-failed": plan(
    5,
    "error",
    "runtime.trace",
    "runtime",
    "runtime-instance",
    "high",
    "Imported runtime trace evidence is high confidence when attributed.",
  ),
  "runtime/shared-mismatch": plan(
    5,
    "error",
    "runtime.trace",
    "runtime",
    "runtime-instance",
    "high",
    "Imported runtime trace evidence is high confidence when attributed.",
  ),
  "runtime/remote-unknown": plan(
    5,
    "warning",
    "runtime.trace",
    "runtime",
    "runtime-instance",
    "high",
    "Imported runtime trace evidence is high confidence when attributed.",
  ),
  "runtime/error-correlated": plan(
    5,
    "error",
    "runtime.trace",
    "runtime",
    "runtime-instance",
    "high",
    "Imported runtime trace evidence is high confidence when attributed.",
  ),
  "bridge/react-version-entry-prefer": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Bridge entry and React major are declared/installed metadata.",
  ),
  "bridge/react-dom-prefix-missing": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared Bridge entry and shared keys are exact for this shape check.",
  ),
  "bridge/lazy-plugin-unregistered": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared Bridge deps and runtimePlugins are exact for this shape check.",
  ),
  "bridge/router-implicit-enable": plan(
    1,
    "info",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared Bridge package presence and bridge options are exact for this shape check.",
  ),
  "bridge/router-shared-conflict": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared Bridge router options and shared keys are exact for this shape check.",
  ),
  "bridge/react-version-entry-mismatch": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Bridge entry and React major are declared/installed metadata.",
  ),
  "bridge/provider-shape-invalid": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "medium",
    "Source heuristics on Bridge factory calls; pass-unknown when sources are thin.",
  ),
  "bridge/ssr-server-entry-leak": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Node/SSR target facts and Bridge import entries are declared metadata.",
  ),
  "bridge/missing-fallback-loading": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "medium",
    "Source heuristics for Bridge consumer fallback/loading options.",
  ),
  "bridge/consumer-api-manual": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "medium",
    "Remotes plus Bridge presence without helper imports is a soft advisory.",
  ),
  "bridge/export-app-missing": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared exposes keys are exact for the export-app convention check.",
  ),
  "bridge/ssr-instanceid-hydration": plan(
    1,
    "info",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared bridge.instanceId and SSR target facts are exact for this advisory.",
  ),
  "bridge/tanstack-router-conflict": plan(
    1,
    "info",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared Bridge router options and TanStack package presence are exact.",
  ),
  "bridge/disable-alias-deprecated": plan(
    1,
    "info",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared bridge.disableAlias is exact for this deprecation advisory.",
  ),
  "ssr/node-remote-manifest": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Node/SSR target facts and remote entry URLs are declared metadata.",
  ),
  "ssr/node-runtime-plugin-missing": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared runtimePlugins and node/SSR target facts are exact for this check.",
  ),
  "ssr/node-library-dts": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared library/dts options on node/SSR producers are exact for this advisory.",
  ),
  "bridge/vue-share-missing": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared Vue Bridge package presence and shared keys are exact for this check.",
  ),
  "bridge/vue-ssr-fresh-context": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "medium",
    "SSR target plus source heuristics for fresh Vue Bridge context; pass-unknown when sources are thin.",
  ),
  "bridge/vue-server-entry": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Node/SSR target facts and Vue Bridge import entries are declared metadata.",
  ),
  "bridge/vue-consumer-manual": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "medium",
    "Remotes plus Vue Bridge presence without helper imports is a soft advisory.",
  ),
};

const evidenceReadsByRule: Record<string, readonly string[]> = {
  "artifact/dts-disabled": ["project.scope", "moduleFederation"],
  "artifact/expose-missing": ["project.scope", "moduleFederation", "artifacts.manifest"],
  "artifact/manifest-assets-disabled": ["project.scope", "moduleFederation"],
  "artifact/manifest-disabled": [
    "project.scope",
    "moduleFederation",
    "capabilities.manifest",
    "artifacts.manifestExplicitlyDisabled",
  ],
  "artifact/manifest-expose-assets-empty": [
    "project.scope",
    "moduleFederation",
    "artifacts.manifest",
    "bundler.name",
  ],
  "artifact/manifest-invalid": ["project.scope", "artifacts.manifestValidity"],
  "artifact/manifest-name-mismatch": ["project.scope", "moduleFederation", "artifacts.manifest"],
  "artifact/manifest-remote-entry-missing": [
    "project.scope",
    "artifacts.manifest",
    "artifacts.emittedAssets",
    "artifacts.assetSizes",
    "capabilities.emittedAssets",
  ],
  "artifact/manifest-shared-version-mismatch": [
    "project.scope",
    "artifacts.manifest",
    "dependencies.installed",
  ],
  "artifact/public-path-non-string-manifest": [
    "project.scope",
    "moduleFederation",
    "bundler.outputPublicPathKind",
  ],
  "artifact/public-path-suspicious": ["project.scope", "artifacts.manifest"],
  "artifact/react-dom-server-in-web": [
    "project.scope",
    "moduleFederation",
    "imports.specifiers",
    "imports.deepImports",
    "artifacts.manifest",
    "artifacts.emittedAssets",
  ],
  "artifact/remote-entry-missing": [
    "project.scope",
    "moduleFederation",
    "artifacts.emittedAssets",
    "capabilities.emittedAssets",
  ],
  "artifact/types-metadata-missing": ["project.scope", "moduleFederation", "artifacts.manifest"],
  "artifact/types-missing": ["project.scope", "artifacts.manifest", "artifacts.emittedAssets"],
  "bridge/lazy-plugin-unregistered": [
    "project.scope",
    "moduleFederation",
    "dependencies.declared",
    "imports.packages",
  ],
  "bridge/react-dom-prefix-missing": [
    "project.scope",
    "moduleFederation",
    "dependencies.declared",
    "imports.packages",
  ],
  "bridge/react-version-entry-prefer": [
    "project.scope",
    "moduleFederation",
    "dependencies.declared",
    "dependencies.installed",
    "imports.packages",
  ],
  "bridge/router-implicit-enable": [
    "project.scope",
    "moduleFederation",
    "dependencies.declared",
    "imports.packages",
  ],
  "bridge/router-shared-conflict": [
    "project.scope",
    "moduleFederation",
    "dependencies.declared",
    "imports.packages",
  ],
  "bridge/react-version-entry-mismatch": [
    "project.scope",
    "moduleFederation",
    "dependencies.declared",
    "dependencies.installed",
    "imports.packages",
  ],
  "bridge/provider-shape-invalid": [
    "project.scope",
    "moduleFederation",
    "dependencies.declared",
    "imports.packages",
    "imports.sourceFiles",
  ],
  "bridge/ssr-server-entry-leak": [
    "project.scope",
    "moduleFederation",
    "dependencies.declared",
    "imports.packages",
    "imports.specifiers",
  ],
  "bridge/missing-fallback-loading": [
    "project.scope",
    "moduleFederation",
    "dependencies.declared",
    "imports.packages",
    "imports.sourceFiles",
  ],
  "bridge/consumer-api-manual": [
    "project.scope",
    "moduleFederation",
    "dependencies.declared",
    "imports.packages",
    "imports.specifiers",
    "imports.sourceScan",
  ],
  "bridge/export-app-missing": ["project.scope", "moduleFederation", "dependencies.declared"],
  "bridge/ssr-instanceid-hydration": [
    "project.scope",
    "moduleFederation",
    "dependencies.declared",
    "imports.packages",
  ],
  "bridge/tanstack-router-conflict": [
    "project.scope",
    "moduleFederation",
    "dependencies.declared",
    "imports.packages",
  ],
  "bridge/disable-alias-deprecated": [
    "project.scope",
    "moduleFederation",
    "dependencies.declared",
    "imports.packages",
  ],
  "ssr/node-remote-manifest": ["project.scope", "moduleFederation"],
  "ssr/node-runtime-plugin-missing": ["project.scope", "moduleFederation"],
  "ssr/node-library-dts": ["project.scope", "moduleFederation"],
  "bridge/vue-share-missing": [
    "project.scope",
    "moduleFederation",
    "dependencies.declared",
    "imports.packages",
  ],
  "bridge/vue-ssr-fresh-context": [
    "project.scope",
    "moduleFederation",
    "dependencies.declared",
    "imports.packages",
    "imports.sourceFiles",
    "imports.sourceScan",
  ],
  "bridge/vue-server-entry": [
    "project.scope",
    "moduleFederation",
    "dependencies.declared",
    "imports.packages",
    "imports.specifiers",
    "imports.sourceScan",
  ],
  "bridge/vue-consumer-manual": [
    "project.scope",
    "moduleFederation",
    "dependencies.declared",
    "imports.packages",
    "imports.sourceFiles",
    "imports.sourceScan",
  ],
  "config/dts-output-dir-mismatch": ["project.scope", "moduleFederation"],
  "config/copied-webpack-options-on-vite": ["project.scope", "moduleFederation", "bundler.name"],
  "config/duplicate-plugin-registration": [
    "project.scope",
    "bundler.moduleFederationPluginCount",
    "bundler.federationInstances",
  ],
  "config/eager-tree-shaking-conflict": ["project.scope", "moduleFederation"],
  "config/async-boundary-missing": [
    "project.scope",
    "moduleFederation",
    "imports.sourceFiles",
    "imports.sourceScan",
  ],
  "config/expose-key-invalid": ["project.scope", "moduleFederation"],
  "config/expose-path-missing": [
    "project.scope",
    "moduleFederation",
    "imports.sourceFiles",
    "imports.sourceScan",
  ],
  "config/external-runtime-conflict": ["project.scope", "moduleFederation"],
  "config/external-runtime-with-exposes": ["project.scope", "moduleFederation"],
  "config/filename-invalid": ["project.scope", "moduleFederation"],
  "config/get-public-path-invalid": ["project.scope", "moduleFederation"],
  "config/get-public-path-unused": ["project.scope", "moduleFederation"],
  "config/implementation-suspicious": ["project.scope", "moduleFederation"],
  "config/library-remote-type-mismatch": ["project.scope", "moduleFederation"],
  "config/name-required": ["project.scope", "project.moduleFederation"],
  "config/plugin-package-mismatch": ["project.scope", "bundler.name", "dependencies.declared"],
  "config/rsbuild-mf-api-generation": [
    "project.scope",
    "bundler.name",
    "moduleFederation",
    "canonicalConfig",
    "dependencies.declared",
    "dependencies.installed",
  ],
  "config/remote-alias-prefix-collision": ["project.scope", "moduleFederation"],
  "config/remote-capability-disabled": ["project.scope", "moduleFederation"],
  "config/remote-entry-invalid": ["project.scope", "moduleFederation"],
  "config/remote-http-insecure": ["project.scope", "moduleFederation"],
  "config/remote-localhost-in-production": ["project.scope", "moduleFederation", "bundler.mode"],
  "config/remote-manifest-recommended": ["project.scope", "moduleFederation"],
  "config/observability-plugin-recommended": [
    "project.scope",
    "moduleFederation",
    "dependencies.declared",
    "dependencies.installed",
    "imports.specifiers",
    "imports.deepImports",
    "imports.sourceScan",
  ],
  "config/runtime-plugin-missing": [
    "project.scope",
    "moduleFederation",
    "imports.sourceFiles",
    "imports.sourceScan",
  ],
  "runtime-plugins/invalid-factory": [
    "project.scope",
    "moduleFederation",
    "runtimePluginContracts",
  ],
  "runtime-plugins/create-script-cors-parity": [
    "project.scope",
    "moduleFederation",
    "runtimePluginContracts",
  ],
  "runtime-plugins/create-script-without-link": [
    "project.scope",
    "moduleFederation",
    "runtimePluginContracts",
  ],
  "config/share-scope-undeclared": ["project.scope", "moduleFederation"],
  "config/shared-capability-disabled": ["project.scope", "moduleFederation"],
  "config/tree-shaking-server-calc-injection": ["project.scope", "moduleFederation"],
  "doctor/partial-analysis": [
    "project.scope",
    "moduleFederation",
    "capabilities",
    "imports.unresolvedDynamic",
  ],
  "federation/circular-remote-graph": ["project.scope", "federation.graph"],
  "federation/external-runtime-provider-missing": [
    "project.scope",
    "federation.graph",
    "imports.sourceScan",
  ],
  "federation/ghost-shares": ["project.scope", "federation.graph", "imports.sourceScan"],
  "federation/host-gaps": ["project.scope", "federation.graph", "imports.sourceScan"],
  "federation/missing-provider": ["project.scope", "federation.graph", "imports.sourceScan"],
  "federation/name-conflict": ["project.scope", "federation.graph"],
  "federation/share-scope-mismatch": ["project.scope", "federation.graph"],
  "federation/share-strategy-mismatch": ["project.scope", "federation.graph"],
  "federation/version-conflict": ["project.scope", "federation.graph"],
  "performance/asset-budget": ["project.scope", "artifacts.manifest", "artifacts.assetSizes"],
  "performance/version-first-startup": ["project.scope", "moduleFederation"],
  "performance/vite-bundle-all-css": ["project.scope", "moduleFederation", "bundler.name"],
  "reliability/async-startup-library-promise": ["project.scope", "moduleFederation"],
  "reliability/external-runtime-provider-unverified": ["project.scope", "moduleFederation"],
  "reliability/shared-import-false": ["project.scope", "moduleFederation"],
  "reliability/snapshot-capability-disabled": ["project.scope", "moduleFederation"],
  "reliability/tree-shaking-server-calc-contract": ["project.scope", "moduleFederation"],
  "reliability/version-first-offline-remotes": ["project.scope", "moduleFederation"],
  "reliability/vite-fixed-parse-timeout": ["project.scope", "moduleFederation", "bundler.name"],
  "vite/remotes-prefer-module": ["project.scope", "moduleFederation", "bundler.name"],
  "vite/var-filename-interop": ["project.scope", "moduleFederation", "bundler.name"],
  "vite/host-init-inject-ssr": [
    "project.scope",
    "moduleFederation",
    "bundler.name",
    "builds",
    "dependencies.declared",
  ],
  "vite/ssr-nitro-externals": [
    "project.scope",
    "moduleFederation",
    "bundler.name",
    "builds",
    "dependencies.declared",
  ],
  "vite/manual-chunks-conflict": [
    "project.scope",
    "moduleFederation",
    "bundler.name",
    "bundler.viteConfig",
  ],
  "vite/hashed-remote-filename": ["project.scope", "moduleFederation", "bundler.name"],
  "vite/remote-hmr-dev": [
    "project.scope",
    "moduleFederation",
    "bundler.name",
    "bundler.mode",
    "builds",
  ],
  "vite/alias-share-bypass": [
    "project.scope",
    "moduleFederation",
    "bundler.name",
    "bundler.viteConfig",
  ],
  "vite/server-origin": ["project.scope", "moduleFederation", "bundler.name", "bundler.viteConfig"],
  "config/transform-import-share-conflict": [
    "project.scope",
    "moduleFederation",
    "bundler.transformImportLibraries",
  ],
  "runtime/error-correlated": ["project.scope", "runtime.trace"],
  "runtime/init-failed": ["project.scope", "runtime.trace"],
  "runtime/remote-load-failed": ["project.scope", "runtime.trace"],
  "runtime/remote-unknown": ["project.scope", "runtime.trace"],
  "runtime/shared-mismatch": ["project.scope", "runtime.trace"],
  "security/get-public-path-dynamic-code": ["project.scope", "moduleFederation"],
  "shared/candidate": [
    "project.scope",
    "moduleFederation",
    "imports.packages",
    "dependencies.declared",
  ],
  "shared/react-host-missing": [
    "project.scope",
    "moduleFederation",
    "imports.packages",
    "imports.dynamicPackages",
  ],
  "shared/deep-import-bypass": [
    "project.scope",
    "moduleFederation",
    "imports.deepImports",
    "imports.deepImportFiles",
  ],
  "shared/prefix-share-recommended": [
    "project.scope",
    "moduleFederation",
    "imports.deepImports",
    "imports.deepImportFiles",
  ],
  "shared/subpath-version-unresolved": [
    "project.scope",
    "moduleFederation",
    "dependencies.installed",
  ],
  "shared/eager-without-singleton": ["project.scope", "moduleFederation"],
  "shared/singleton-mismatch": ["project.scope", "federation.graph"],
  "shared/singleton-risk": ["project.scope", "moduleFederation"],
  "shared/unused": [
    "project.scope",
    "moduleFederation",
    "imports.packages",
    "imports.dynamicPackages",
    "imports.specifiers",
    "imports.deepImports",
    "imports.unresolvedDynamic",
    "imports.sourceScan",
  ],
  "shared/version-unsatisfied": ["project.scope", "moduleFederation", "dependencies.installed"],
};

function selectorFor(path: string, spec: RulePlan): EvidenceRequirement {
  const predicate =
    path === "config.declared"
      ? "project.moduleFederation"
      : path === "source.scan"
        ? "project.imports"
        : path === "imports.sourceScan"
          ? "imports.sourceScan"
          : path;
  const layer =
    predicate === "runtime.trace"
      ? "runtime"
      : predicate === "project.imports"
        ? "effective"
        : predicate === "federation.graph" ||
            predicate === "project.scope" ||
            predicate === "moduleFederation" ||
            predicate === "project.moduleFederation"
          ? "declared"
          : predicate.startsWith("artifacts.")
            ? "artifact"
            : "effective";
  const subjectKind =
    predicate === "runtime.trace"
      ? "runtime-instance"
      : predicate.startsWith("artifacts.")
        ? "artifact"
        : spec.subjectKind;
  return {
    predicate,
    layer,
    subjectKind,
    minimumConfidence: spec.confidenceCeiling,
    minimumCompleteness: "complete",
  };
}

function requirementFor(id: string, spec: RulePlan): EvidenceRequirement {
  const reads = evidenceReadsByRule[id];
  if (!reads) throw new Error(`Evidence prerequisites are missing for ${id}`);
  if (id === "config/duplicate-plugin-registration") {
    return {
      allOf: [
        selectorFor("project.scope", spec),
        {
          anyOf: [
            selectorFor("bundler.moduleFederationPluginCount", spec),
            selectorFor("bundler.federationInstances", spec),
          ],
        },
      ],
    };
  }
  const optionalPluginFacts: Record<string, readonly string[]> = {
    "doctor/partial-analysis": ["moduleFederation"],
    "vite/host-init-inject-ssr": ["builds"],
    "vite/ssr-nitro-externals": ["builds"],
    "vite/manual-chunks-conflict": ["bundler.viteConfig"],
    "vite/alias-share-bypass": ["bundler.viteConfig"],
    "vite/server-origin": ["bundler.viteConfig"],
    "vite/remote-hmr-dev": ["builds"],
    "config/transform-import-share-conflict": ["bundler.transformImportLibraries"],
    "config/rsbuild-mf-api-generation": ["canonicalConfig", "dependencies.installed"],
  };
  const optional = optionalPluginFacts[id];
  if (optional) {
    return {
      allOf: reads
        .filter((path) => !optional.includes(path))
        .map((path) => selectorFor(path, spec)),
    };
  }
  return { allOf: reads.map((path) => selectorFor(path, spec)) };
}

function applicabilityFor(spec: RulePlan): RuleApplicability {
  return {
    adapters: spec.adapters.map((name) => ({ name })),
    bundlers: spec.bundlers.map((name) => ({ name })),
  };
}

function inventoryStatusFor(id: string): RuleMigrationStatus {
  if (COMPATIBILITY_EXCEPTION_IDS.has(id)) return "legacy";
  if (MIGRATED_RULE_IDS.has(id)) return "migrated";
  throw new Error(`Built-in ${id} is neither migrated nor documented as a compatibility exception`);
}

function migrationNoteFor(id: string, spec: RulePlan): string {
  if (COMPATIBILITY_EXCEPTION_IDS.has(id)) {
    const exception = RULE_COMPATIBILITY_EXCEPTIONS.find((entry) => entry.id === id);
    if (!exception) throw new Error(`Missing compatibility exception metadata for ${id}`);
    return `Group ${spec.group}; compatibility-only exception (${exception.reason}). ${exception.deprecationPlan}`;
  }
  return `Group ${spec.group}; ${spec.confidenceReason} Migrated through the evidence-aware rollout bridge with golden V1 parity in shadow and v2-compat modes.`;
}

/** Machine-readable migration ledger for every current built-in. */
export const ruleInventory: readonly RuleInventoryEntry[] = ids.map((id) => {
  const spec = plans[id];
  const guidance = ruleGuidance[id];
  const evidenceReads = evidenceReadsByRule[id];
  if (!spec || !guidance || !evidenceReads)
    throw new Error(`Rule inventory is incomplete for ${id}`);
  return {
    id,
    version: "1",
    owner: { name: "MFDoctor maintainers" },
    remediation: {
      summary: guidance.impact,
      documentation: `/rules/${id}`,
      fix: guidance.fix,
    },
    prerequisites: requirementFor(id, spec),
    applicability: applicabilityFor(spec),
    confidenceCeiling: spec.confidenceCeiling,
    defaultSeverity: spec.severity,
    group: spec.group,
    status: inventoryStatusFor(id),
    evidenceReads,
    migrationNote: migrationNoteFor(id, spec),
  };
});

export const ruleInventoryIds = ids;
