import type {
  EvidenceAwareRuleMeta,
  EvidenceRequirement,
  RuleApplicability,
} from "./rule-contract.js";
import { ruleGuidance } from "./rule-guidance.js";

export type RuleMigrationGroup = 0 | 1 | 2 | 3 | 4 | 5 | 6;
export type RuleMigrationStatus = "legacy" | "migrated";

export interface RuleInventoryEntry extends EvidenceAwareRuleMeta {
  group: RuleMigrationGroup;
  status: RuleMigrationStatus;
  migrationNote: string;
}

const ids = [
  "artifact/dts-disabled",
  "artifact/expose-missing",
  "artifact/manifest-assets-disabled",
  "artifact/manifest-disabled",
  "artifact/manifest-expose-assets-empty",
  "artifact/manifest-invalid",
  "artifact/manifest-name-mismatch",
  "artifact/manifest-remote-entry-missing",
  "artifact/manifest-shared-version-mismatch",
  "artifact/public-path-non-string-manifest",
  "artifact/public-path-suspicious",
  "artifact/remote-entry-missing",
  "artifact/types-metadata-missing",
  "artifact/types-missing",
  "config/dts-output-dir-mismatch",
  "config/duplicate-plugin-registration",
  "config/eager-tree-shaking-conflict",
  "config/expose-key-invalid",
  "config/expose-path-missing",
  "config/external-runtime-conflict",
  "config/external-runtime-with-exposes",
  "config/filename-invalid",
  "config/get-public-path-invalid",
  "config/get-public-path-unused",
  "config/implementation-suspicious",
  "config/library-remote-type-mismatch",
  "config/name-required",
  "config/nested-producer-dts-extract",
  "config/plugin-package-mismatch",
  "config/remote-alias-prefix-collision",
  "config/remote-capability-disabled",
  "config/remote-entry-invalid",
  "config/remote-http-insecure",
  "config/remote-localhost-in-production",
  "config/remote-manifest-recommended",
  "config/remote-type-urls-missing",
  "config/runtime-plugin-missing",
  "config/share-scope-undeclared",
  "config/shared-capability-disabled",
  "config/shared-externals-conflict",
  "config/tree-shaking-server-calc-injection",
  "doctor/partial-analysis",
  "federation/circular-remote-graph",
  "federation/external-runtime-provider-missing",
  "federation/ghost-shares",
  "federation/host-gaps",
  "federation/missing-provider",
  "federation/name-conflict",
  "federation/share-scope-mismatch",
  "federation/share-strategy-mismatch",
  "federation/version-conflict",
  "performance/asset-budget",
  "performance/version-first-startup",
  "performance/vite-bundle-all-css",
  "reliability/async-startup-library-promise",
  "reliability/external-runtime-provider-unverified",
  "reliability/shared-import-false",
  "reliability/snapshot-capability-disabled",
  "reliability/tree-shaking-server-calc-contract",
  "reliability/version-first-offline-remotes",
  "reliability/vite-fixed-parse-timeout",
  "runtime/error-correlated",
  "runtime/init-failed",
  "runtime/remote-load-failed",
  "runtime/remote-unknown",
  "runtime/shared-mismatch",
  "security/get-public-path-dynamic-code",
  "shared/candidate",
  "shared/deep-import-bypass",
  "shared/eager-without-singleton",
  "shared/singleton-mismatch",
  "shared/singleton-risk",
  "shared/unused",
  "shared/version-unsatisfied",
] as const;

type RulePlan = {
  group: RuleMigrationGroup;
  severity: "error" | "warning" | "info";
  predicate: string;
  layer: "declared" | "artifact" | "runtime";
  subjectKind:
    | "project"
    | "dependency"
    | "shared-package"
    | "build"
    | "artifact"
    | "runtime-instance";
  confidenceCeiling: "exact" | "high" | "medium" | "low" | "unknown";
  adapters: readonly string[];
  bundlers: readonly string[];
  confidenceReason: string;
};

const ALL = ["vite", "rspack", "rsbuild", "webpack", "modern"] as const;
const VITE = ["vite"] as const;
const plan = (
  group: RuleMigrationGroup,
  severity: RulePlan["severity"],
  predicate: string,
  layer: RulePlan["layer"],
  subjectKind: RulePlan["subjectKind"],
  confidenceCeiling: RulePlan["confidenceCeiling"],
  confidenceReason: string,
  bundlers: readonly string[] = ALL,
): RulePlan => ({
  group,
  severity,
  predicate,
  layer,
  subjectKind,
  confidenceCeiling,
  adapters: bundlers,
  bundlers,
  confidenceReason,
});

/** Explicit plan for every current built-in. No plan may fall back to a group default. */
const plans: Record<string, RulePlan> = {
  "config/name-required": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/expose-key-invalid": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/expose-path-missing": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/remote-entry-invalid": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/filename-invalid": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/remote-http-insecure": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/remote-localhost-in-production": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/duplicate-plugin-registration": plan(
    2,
    "error",
    "compiler.plugin-registration",
    "artifact",
    "build",
    "exact",
    "Compiler registration evidence is exact when collected.",
  ),
  "config/remote-alias-prefix-collision": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/nested-producer-dts-extract": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/dts-output-dir-mismatch": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/remote-type-urls-missing": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "artifact/public-path-non-string-manifest": plan(
    2,
    "warning",
    "artifact.manifest",
    "artifact",
    "artifact",
    "exact",
    "Parsed manifest evidence is exact when valid.",
  ),
  "config/remote-manifest-recommended": plan(
    1,
    "info",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/library-remote-type-mismatch": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/share-scope-undeclared": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/runtime-plugin-missing": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/get-public-path-invalid": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/get-public-path-unused": plan(
    1,
    "info",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "security/get-public-path-dynamic-code": plan(
    3,
    "warning",
    "source.scan",
    "declared",
    "project",
    "low",
    "Source scans are heuristic and cannot claim exact confidence.",
  ),
  "config/implementation-suspicious": plan(
    1,
    "info",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/external-runtime-with-exposes": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/external-runtime-conflict": plan(
    2,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/remote-capability-disabled": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "config/shared-capability-disabled": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "reliability/snapshot-capability-disabled": plan(
    6,
    "warning",
    "analysis.capability",
    "declared",
    "project",
    "unknown",
    "Capability evidence is not yet normalized by the evidence protocol.",
  ),
  "config/eager-tree-shaking-conflict": plan(
    1,
    "error",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "reliability/external-runtime-provider-unverified": plan(
    6,
    "warning",
    "analysis.capability",
    "declared",
    "project",
    "unknown",
    "Capability evidence is not yet normalized by the evidence protocol.",
  ),
  "reliability/async-startup-library-promise": plan(
    6,
    "warning",
    "analysis.capability",
    "declared",
    "project",
    "unknown",
    "Capability evidence is not yet normalized by the evidence protocol.",
  ),
  "performance/version-first-startup": plan(
    6,
    "info",
    "analysis.capability",
    "declared",
    "project",
    "unknown",
    "Capability evidence is not yet normalized by the evidence protocol.",
  ),
  "performance/asset-budget": plan(
    2,
    "warning",
    "artifact.asset-size",
    "artifact",
    "artifact",
    "exact",
    "Collected asset sizes are exact when complete.",
  ),
  "reliability/version-first-offline-remotes": plan(
    6,
    "warning",
    "analysis.capability",
    "declared",
    "project",
    "unknown",
    "Capability evidence is not yet normalized by the evidence protocol.",
  ),
  "reliability/shared-import-false": plan(
    6,
    "warning",
    "analysis.capability",
    "declared",
    "project",
    "unknown",
    "Capability evidence is not yet normalized by the evidence protocol.",
  ),
  "config/tree-shaking-server-calc-injection": plan(
    1,
    "warning",
    "config.declared",
    "declared",
    "project",
    "high",
    "Declared config is exact for this shape check.",
  ),
  "reliability/tree-shaking-server-calc-contract": plan(
    6,
    "warning",
    "analysis.capability",
    "declared",
    "project",
    "unknown",
    "Capability evidence is not yet normalized by the evidence protocol.",
  ),
  "performance/vite-bundle-all-css": plan(
    6,
    "warning",
    "analysis.capability",
    "declared",
    "project",
    "unknown",
    "Capability evidence is not yet normalized by the evidence protocol.",
    VITE,
  ),
  "reliability/vite-fixed-parse-timeout": plan(
    6,
    "info",
    "analysis.capability",
    "declared",
    "project",
    "unknown",
    "Capability evidence is not yet normalized by the evidence protocol.",
    VITE,
  ),
  "artifact/manifest-assets-disabled": plan(
    2,
    "warning",
    "artifact.manifest",
    "artifact",
    "artifact",
    "exact",
    "Parsed manifest evidence is exact when valid.",
  ),
  "artifact/manifest-disabled": plan(
    2,
    "info",
    "artifact.manifest",
    "artifact",
    "artifact",
    "exact",
    "Parsed manifest evidence is exact when valid.",
  ),
  "artifact/dts-disabled": plan(
    2,
    "warning",
    "artifact.types",
    "artifact",
    "artifact",
    "exact",
    "Collected type artifact evidence is exact when complete.",
  ),
  "config/shared-externals-conflict": plan(
    0,
    "error",
    "compiler.externals",
    "artifact",
    "build",
    "unknown",
    "Real compiler externals are required; synthetic package data is not valid.",
  ),
  "shared/version-unsatisfied": plan(
    3,
    "error",
    "dependency.package",
    "declared",
    "dependency",
    "medium",
    "Package metadata is exact only after provenance and version resolution are verified.",
  ),
  "artifact/manifest-invalid": plan(
    2,
    "error",
    "artifact.manifest",
    "artifact",
    "artifact",
    "exact",
    "Parsed manifest evidence is exact when valid.",
  ),
  "artifact/manifest-name-mismatch": plan(
    2,
    "error",
    "artifact.manifest",
    "artifact",
    "artifact",
    "exact",
    "Parsed manifest evidence is exact when valid.",
  ),
  "artifact/manifest-remote-entry-missing": plan(
    2,
    "error",
    "artifact.manifest",
    "artifact",
    "artifact",
    "exact",
    "Parsed manifest evidence is exact when valid.",
  ),
  "artifact/manifest-expose-assets-empty": plan(
    2,
    "warning",
    "artifact.manifest",
    "artifact",
    "artifact",
    "exact",
    "Parsed manifest evidence is exact when valid.",
  ),
  "artifact/manifest-shared-version-mismatch": plan(
    2,
    "warning",
    "artifact.manifest",
    "artifact",
    "artifact",
    "exact",
    "Parsed manifest evidence is exact when valid.",
  ),
  "artifact/types-metadata-missing": plan(
    2,
    "warning",
    "artifact.types",
    "artifact",
    "artifact",
    "exact",
    "Collected type artifact evidence is exact when complete.",
  ),
  "artifact/remote-entry-missing": plan(
    2,
    "error",
    "artifact.remote-entry",
    "artifact",
    "artifact",
    "exact",
    "Collected remote entry evidence is exact when complete.",
  ),
  "artifact/expose-missing": plan(
    2,
    "error",
    "artifact.expose",
    "artifact",
    "artifact",
    "exact",
    "Collected expose artifact evidence is exact when complete.",
  ),
  "doctor/partial-analysis": plan(
    6,
    "warning",
    "analysis.capability",
    "declared",
    "project",
    "unknown",
    "Capability evidence is not yet normalized by the evidence protocol.",
  ),
  "config/plugin-package-mismatch": plan(
    3,
    "warning",
    "dependency.package",
    "declared",
    "dependency",
    "medium",
    "Package metadata is exact only after provenance and version resolution are verified.",
  ),
  "shared/singleton-risk": plan(
    3,
    "warning",
    "dependency.package",
    "declared",
    "shared-package",
    "low",
    "Shared package scans are heuristic and cannot claim exact confidence.",
  ),
  "shared/eager-without-singleton": plan(
    3,
    "warning",
    "dependency.package",
    "declared",
    "shared-package",
    "low",
    "Shared package scans are heuristic and cannot claim exact confidence.",
  ),
  "shared/unused": plan(
    3,
    "warning",
    "source.scan",
    "declared",
    "shared-package",
    "low",
    "Absence from a source scan is heuristic and needs complete scan evidence.",
  ),
  "shared/candidate": plan(
    3,
    "info",
    "source.scan",
    "declared",
    "shared-package",
    "low",
    "Shared package scans are heuristic and cannot claim exact confidence.",
  ),
  "shared/deep-import-bypass": plan(
    3,
    "warning",
    "source.scan",
    "declared",
    "shared-package",
    "low",
    "Shared package scans are heuristic and cannot claim exact confidence.",
  ),
  "artifact/public-path-suspicious": plan(
    2,
    "warning",
    "artifact.public-path",
    "artifact",
    "artifact",
    "high",
    "Artifact public-path evidence is exact when the artifact is complete.",
  ),
  "artifact/types-missing": plan(
    2,
    "warning",
    "artifact.types",
    "artifact",
    "artifact",
    "exact",
    "Collected type artifact evidence is exact when complete.",
  ),
  "federation/name-conflict": plan(
    4,
    "error",
    "federation.graph",
    "declared",
    "project",
    "high",
    "Federation graph evidence is high confidence when all projects are present.",
  ),
  "federation/version-conflict": plan(
    4,
    "error",
    "federation.graph",
    "declared",
    "shared-package",
    "high",
    "Federation graph evidence is high confidence when all projects are present.",
  ),
  "federation/share-scope-mismatch": plan(
    4,
    "error",
    "federation.graph",
    "declared",
    "shared-package",
    "high",
    "Federation graph evidence is high confidence when all projects are present.",
  ),
  "federation/share-strategy-mismatch": plan(
    4,
    "warning",
    "federation.graph",
    "declared",
    "project",
    "high",
    "Federation graph evidence is high confidence when all projects are present.",
  ),
  "federation/circular-remote-graph": plan(
    4,
    "warning",
    "federation.graph",
    "declared",
    "project",
    "high",
    "Federation graph evidence is high confidence when all projects are present.",
  ),
  "federation/missing-provider": plan(
    4,
    "error",
    "federation.graph",
    "declared",
    "shared-package",
    "high",
    "Federation graph evidence is high confidence when all projects are present.",
  ),
  "federation/host-gaps": plan(
    4,
    "warning",
    "federation.graph",
    "declared",
    "project",
    "high",
    "Federation graph evidence is high confidence when all projects are present.",
  ),
  "federation/ghost-shares": plan(
    4,
    "info",
    "federation.graph",
    "declared",
    "shared-package",
    "high",
    "Federation graph evidence is high confidence when all projects are present.",
  ),
  "shared/singleton-mismatch": plan(
    4,
    "warning",
    "federation.graph",
    "declared",
    "shared-package",
    "high",
    "Federation graph evidence is high confidence when all projects are present.",
  ),
  "federation/external-runtime-provider-missing": plan(
    4,
    "error",
    "federation.graph",
    "declared",
    "project",
    "high",
    "Federation graph evidence is high confidence when all projects are present.",
  ),
  "runtime/remote-load-failed": plan(
    5,
    "error",
    "runtime.trace",
    "runtime",
    "runtime-instance",
    "high",
    "Imported runtime trace evidence is high confidence when attributed.",
  ),
  "runtime/init-failed": plan(
    5,
    "error",
    "runtime.trace",
    "runtime",
    "runtime-instance",
    "high",
    "Imported runtime trace evidence is high confidence when attributed.",
  ),
  "runtime/shared-mismatch": plan(
    5,
    "error",
    "runtime.trace",
    "runtime",
    "runtime-instance",
    "high",
    "Imported runtime trace evidence is high confidence when attributed.",
  ),
  "runtime/remote-unknown": plan(
    5,
    "warning",
    "runtime.trace",
    "runtime",
    "runtime-instance",
    "high",
    "Imported runtime trace evidence is high confidence when attributed.",
  ),
  "runtime/error-correlated": plan(
    5,
    "error",
    "runtime.trace",
    "runtime",
    "runtime-instance",
    "high",
    "Imported runtime trace evidence is high confidence when attributed.",
  ),
};

function requirementFor(spec: RulePlan): EvidenceRequirement {
  return {
    predicate: spec.predicate,
    layer: spec.layer,
    subjectKind: spec.subjectKind,
    minimumConfidence: spec.confidenceCeiling,
    minimumCompleteness: "complete",
  };
}

function applicabilityFor(spec: RulePlan): RuleApplicability {
  return {
    adapters: spec.adapters.map((name) => ({ name })),
    bundlers: spec.bundlers.map((name) => ({ name })),
  };
}

/** Machine-readable migration ledger. Legacy entries are intentionally not wired into runtime yet. */
export const ruleInventory: readonly RuleInventoryEntry[] = ids.map((id) => {
  const spec = plans[id];
  const guidance = ruleGuidance[id];
  if (!spec || !guidance) throw new Error(`Rule inventory is incomplete for ${id}`);
  return {
    id,
    version: "1",
    owner: { name: "Module Federation Doctor maintainers" },
    remediation: {
      summary: guidance.impact,
      documentation: `/rules/${id}`,
      fix: guidance.fix,
    },
    prerequisites: requirementFor(spec),
    applicability: applicabilityFor(spec),
    confidenceCeiling: spec.confidenceCeiling,
    defaultSeverity: spec.severity,
    group: spec.group,
    status: "legacy",
    migrationNote: `Planned group ${spec.group}; ${spec.confidenceReason} Current v1 behavior remains unchanged until migration.`,
  };
});

export const ruleInventoryIds = ids;
