import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  AnalysisBudgetTracker,
  AnalysisContentCache,
  DEFAULT_ALWAYS_SHARED,
  DEFAULT_ANALYSIS_BUDGETS,
  DEFAULT_DEEP_IMPORT_ALLOWLIST,
  DEFAULT_EXCLUDE,
  DEFAULT_IMPORT_DEPTH,
  DEFAULT_INCLUDE,
  DEFAULT_PROMPT_FINDINGS,
  DEFAULT_SHARE_CANDIDATE_PACKAGES,
  DEFAULT_SINGLETON_RISK_PACKAGES,
  DEFAULT_WORKSPACE_PROJECT_GLOBS,
  DIAGNOSTICS_PROMPTS_ENV,
  DOCTOR_PRESET_NAMES,
  EVIDENCE_LEGACY_ENV,
  EvidenceBudgetExceededError,
  EvidenceIntegrityError,
  EvidenceProjectionError,
  EvidenceReaderError,
  EvidenceResourceError,
  FINDING_DETAILS_SCHEMAS,
  INCOMPLETE_REASON_CODES,
  MAX_DIAGNOSTICS_PROMPT_FINDINGS,
  ParityResourceError,
  ProbeError,
  RELEASE_GATES,
  ROLLOUT_SCOPES,
  RULE_DEMO_COVERAGE,
  RolloutGateError,
  RuntimeTraceError,
  TYPED_DETAILS_RULE_IDS,
  WORKSPACE_IGNORE,
  analysisCacheKey,
  analyze,
  analyzeFederation,
  analyzeRuntime,
  applyBaseline,
  assertDriftLedgerEntry,
  assertEvidenceGraphIntegrity,
  assertEvidenceValue,
  assertInventoryDemoCoverage,
  attachRuntimeTraceEvidence,
  buildAgentPrompt,
  buildUiPayload,
  builtInRules,
  canonicalizeEvidenceValue,
  capConfidence,
  classifyRuntimeAttribution,
  coerceFederationInstanceInputs,
  compareManifests,
  compareToSarif,
  compareV1Outputs,
  computeHealthScore,
  computeRunStatus,
  contentDigest,
  correlateRuntime,
  createAnalysisCacheIdentity,
  createEvidenceRolloutController,
  createWorkspaceApplicationIdentity,
  definePolicyPack,
  defineRule,
  demoPreset,
  describeFederationInstances,
  discoverWorkspaceProjects,
  discoverWorkspaceProjectsWithBudget,
  duplicateFederationInstanceGroups,
  emptyRunStatus,
  entryMatchesFinding,
  federationConfigDigest,
  federationInstanceRefs,
  findPromptTarget,
  findingDetails,
  formatCompareTerminal,
  formatTopAgentPrompts,
  generateBaseline,
  hasMf2SharedArrayManifest,
  hasMfBridgeEntryExpose,
  hasMfSsrFragmentRemotes,
  hasMfToolkitShapeSignals,
  isCiEnvironment,
  isDoctorPresetName,
  isExcludedFromScore,
  isKnownFindingDetailsSchema,
  isMf2SharedArrayManifestOnly,
  isMfBridgeEntryProducer,
  isMfSsrFragmentProducer,
  isMfSsrFragmentRemoteEntry,
  labelForScore,
  loadBaseline,
  loadManifestContract,
  loadRuntimeTraceFile,
  measureEvidenceUsage,
  mergeSharedPolicy,
  migrateDoctorReport,
  migrateProjectFacts,
  normalizeEvidenceGraph,
  parseBaseline,
  parseRuntimeTraces,
  policyFails,
  policyRelevantFindings,
  presets,
  probeManifest,
  productionPreset,
  projectFactsFromEvidence,
  pruneBaseline,
  readCanonicalModuleFederationConfig,
  readEvidenceDocument,
  readEvidenceFile,
  readFindingDetails,
  recommendedPreset,
  redactEvidenceValue,
  reportFromEvaluations,
  reportFromV2Evaluations,
  reserveEvidenceBudget,
  resolveAnalysisBudgets,
  resolveBaselineOptions,
  resolveDiagnosticsDir,
  resolveDiagnosticsPromptLimit,
  resolveDiagnosticsPromptLimitFromEnv,
  resolveOptions,
  resolvePolicy,
  resolvePrintLog,
  resolvePrompt,
  resolveQuiet,
  ruleInventory,
  ruleInventoryIds,
  runEvidenceAwareRules,
  selectTopFindings,
  stableEvaluationId,
  stableEvidenceId,
  stableSerialize,
  strictPreset,
  summarizeFindings,
  toolkitRecognitionEnabled,
  updateBaseline,
  weakestConfidence,
  workspaceProjectRoot,
  workspaceRootForProjects,
  writeBaselineFile,
  writeCompareReports,
  writeDiagnosticsDump,
} from "../../src/index.js";

const rootEntrySurface = {
  AnalysisBudgetTracker,
  AnalysisContentCache,
  DEFAULT_ALWAYS_SHARED,
  DEFAULT_ANALYSIS_BUDGETS,
  DEFAULT_DEEP_IMPORT_ALLOWLIST,
  DEFAULT_EXCLUDE,
  DEFAULT_IMPORT_DEPTH,
  DEFAULT_INCLUDE,
  DEFAULT_PROMPT_FINDINGS,
  DEFAULT_SHARE_CANDIDATE_PACKAGES,
  DEFAULT_SINGLETON_RISK_PACKAGES,
  DEFAULT_WORKSPACE_PROJECT_GLOBS,
  DIAGNOSTICS_PROMPTS_ENV,
  DOCTOR_PRESET_NAMES,
  EVIDENCE_LEGACY_ENV,
  EvidenceBudgetExceededError,
  EvidenceIntegrityError,
  EvidenceProjectionError,
  EvidenceReaderError,
  EvidenceResourceError,
  FINDING_DETAILS_SCHEMAS,
  INCOMPLETE_REASON_CODES,
  MAX_DIAGNOSTICS_PROMPT_FINDINGS,
  ParityResourceError,
  ProbeError,
  RELEASE_GATES,
  ROLLOUT_SCOPES,
  RULE_DEMO_COVERAGE,
  RolloutGateError,
  RuntimeTraceError,
  TYPED_DETAILS_RULE_IDS,
  WORKSPACE_IGNORE,
  analysisCacheKey,
  analyze,
  analyzeFederation,
  analyzeRuntime,
  applyBaseline,
  assertDriftLedgerEntry,
  assertEvidenceGraphIntegrity,
  assertEvidenceValue,
  assertInventoryDemoCoverage,
  attachRuntimeTraceEvidence,
  buildAgentPrompt,
  buildUiPayload,
  builtInRules,
  canonicalizeEvidenceValue,
  capConfidence,
  classifyRuntimeAttribution,
  coerceFederationInstanceInputs,
  compareManifests,
  compareToSarif,
  compareV1Outputs,
  computeHealthScore,
  computeRunStatus,
  contentDigest,
  correlateRuntime,
  createAnalysisCacheIdentity,
  createEvidenceRolloutController,
  createWorkspaceApplicationIdentity,
  definePolicyPack,
  defineRule,
  demoPreset,
  describeFederationInstances,
  discoverWorkspaceProjects,
  discoverWorkspaceProjectsWithBudget,
  duplicateFederationInstanceGroups,
  emptyRunStatus,
  entryMatchesFinding,
  federationConfigDigest,
  federationInstanceRefs,
  findPromptTarget,
  findingDetails,
  formatCompareTerminal,
  formatTopAgentPrompts,
  generateBaseline,
  hasMf2SharedArrayManifest,
  hasMfBridgeEntryExpose,
  hasMfSsrFragmentRemotes,
  hasMfToolkitShapeSignals,
  isCiEnvironment,
  isDoctorPresetName,
  isExcludedFromScore,
  isKnownFindingDetailsSchema,
  isMf2SharedArrayManifestOnly,
  isMfBridgeEntryProducer,
  isMfSsrFragmentProducer,
  isMfSsrFragmentRemoteEntry,
  labelForScore,
  loadBaseline,
  loadManifestContract,
  loadRuntimeTraceFile,
  measureEvidenceUsage,
  mergeSharedPolicy,
  migrateDoctorReport,
  migrateProjectFacts,
  normalizeEvidenceGraph,
  parseBaseline,
  parseRuntimeTraces,
  policyFails,
  policyRelevantFindings,
  presets,
  probeManifest,
  productionPreset,
  projectFactsFromEvidence,
  pruneBaseline,
  readCanonicalModuleFederationConfig,
  readEvidenceDocument,
  readEvidenceFile,
  readFindingDetails,
  recommendedPreset,
  redactEvidenceValue,
  reportFromEvaluations,
  reportFromV2Evaluations,
  reserveEvidenceBudget,
  resolveAnalysisBudgets,
  resolveBaselineOptions,
  resolveDiagnosticsDir,
  resolveDiagnosticsPromptLimit,
  resolveDiagnosticsPromptLimitFromEnv,
  resolveOptions,
  resolvePolicy,
  resolvePrintLog,
  resolvePrompt,
  resolveQuiet,
  ruleInventory,
  ruleInventoryIds,
  runEvidenceAwareRules,
  selectTopFindings,
  stableEvaluationId,
  stableEvidenceId,
  stableSerialize,
  strictPreset,
  summarizeFindings,
  toolkitRecognitionEnabled,
  updateBaseline,
  weakestConfidence,
  workspaceProjectRoot,
  workspaceRootForProjects,
  writeBaselineFile,
  writeCompareReports,
  writeDiagnosticsDump,
};

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "../..");

function readIndexUnusedExportAllowlist(): string[] {
  const source = readFileSync(join(repoRoot, "scripts/knip-index-export-allowlist.mjs"), "utf8");
  const start = source.indexOf("Object.freeze([");
  const end = source.indexOf("]);", start);
  if (start === -1 || end === -1) {
    throw new Error("knip allowlist array not found");
  }
  const names = [...source.slice(start, end).matchAll(/^\s+"([A-Za-z0-9_]+)",?$/gm)].map(
    (match) => match[1] ?? "",
  );
  return names.filter(Boolean);
}

function valueExportNames(source: string): Set<string> {
  const names = new Set<string>();
  const block = /(?:^|\n)export \{([^}]+)\}/g;
  for (const match of source.matchAll(block)) {
    const body = match[1] ?? "";
    for (const raw of body.split(",")) {
      const name = raw.trim().split(/\s+/)[0];
      if (name) names.add(name);
    }
  }
  return names;
}

describe("root entry unused-export gate", () => {
  it("keeps CLI/engine value exports importable from src/index.ts", () => {
    expect(Object.keys(rootEntrySurface).length).toBeGreaterThan(100);
    expect(rootEntrySurface.analyze).toEqual(expect.any(Function));
    expect(rootEntrySurface.defineRule).toEqual(expect.any(Function));
    expect(rootEntrySurface.definePolicyPack).toEqual(expect.any(Function));
    for (const [name, value] of Object.entries(rootEntrySurface)) {
      expect(value, name).not.toBeUndefined();
    }
  });

  it("keeps the knip allowlist unique and present on the root entry", () => {
    const allowlist = readIndexUnusedExportAllowlist();
    expect(allowlist.length).toBeGreaterThan(0);
    expect(new Set(allowlist).size).toBe(allowlist.length);
    const source = readFileSync(join(repoRoot, "src/index.ts"), "utf8");
    const exported = valueExportNames(source);
    for (const name of allowlist) {
      expect(exported.has(name), name).toBe(true);
      expect(rootEntrySurface, name).not.toHaveProperty(name);
    }
  });
});
